kumuluzee:
  nats:
    jetstream: true
    ack-confirmation-timeout: PT5S
    servers:
      - name: default
        addresses:
          - nats://localhost:4222
        streams:
          - name: stream1
            subjects:
              - subject1
              - subject2
#            description:
#            retention-policy:
#            max-consumers:
#            max-bytes:
#            max-age:
#            max-msgs: 100
#            max-msg-size:
            storage-type: memory
#            replicas:
#            no-ack:
#            template-owner:
#            discard-policy:
#            duplicate-window:
        jetstream-contexts:
          - name: context1
#            domain:
#            prefix:
#            publish-no-ack:
#            request-timeout:
      - name: secure-unverified-client
        addresses:
          - tls://localhost:4223
          - opentls://localhost:4223
        tls:
#          trust-store-path: C:\Users\Matej\IdeaProjects\kumuluzee-nats-core-sample\src\main\resources\certs\truststore.jks
#          trust-store-password: password2
          certificate-path: C:\Users\Matej\IdeaProjects\kumuluzee-nats-core-sample\src\main\resources\certs\server-cert.pem
      - name: secure
        addresses:
          - tls://localhost:4224
        tls:
#          trust-store-path: C:\Users\Matej\IdeaProjects\kumuluzee-nats-core-sample\src\main\resources\certs\truststore.jks
#          trust-store-password: password2
          certificate-path: C:\Users\Matej\IdeaProjects\kumuluzee-nats-core-sample\src\main\resources\certs\server-cert.pem
          key-store-path: C:\Users\Matej\IdeaProjects\kumuluzee-nats-core-sample\src\main\resources\certs\keystore.jks
          key-store-password: password
        streams:
          - name: stream2
            subjects:
              - product.*
#            description:
#            retention-policy:
#            max-consumers:
#            max-bytes:
#            max-age:
#            max-msgs:
#            max-msg-size:
            storage-type: memory
#            replicas:
#            no-ack:
#            template-owner:
#            discard-policy:
#            duplicate-window:
    consumer-configuration:
      - name: custom1
        deliver-policy: all
#        ack-policy:
#        replay-policy:
#        description:
#        durable:
#        deliver-subject:
#        deliver-group:
#        filter-subject:
#        sample-frequency:
#        start-time:
#        ack-wait:
#        idle-heartbeat:
#        max-expires:
#        inactive-threshold:
#        start-seq:
#        max-deliver:
#        rate-limit:
#        max-ack-pending:
#        max-pull-waiting:
#        max-batch:
#        max-bytes:
#        flow-control:
#        headers-only:
#        backoff: